name: drone-test
kind: pipeline
type: docker

steps:
- name: test
  image: python:3
  commands:
  - apt-get update && install mpich
  - pip install pytest
  - pip install .
  - mpirun -n 1 pytest heat/
