name: drone-test
kind: pipeline
type: docker

steps:
- name: test
  image: dhna/mpi4py
  commands:
  - pip install -U numpy pytest
  - pip install .
  - mpirun -n 1 pytest heat/
  - mpirun -n 2 pytest heat/
  - mpirun -n 3 pytest heat/
  - mpirun -n 4 pytest heat/
  - mpirun -n 7 pytest heat/
